api_version = "2025-01"

[[extensions]]
type = "theme"
name = "Atchr Messaging"
handle = "atchr-chat-embed"

[extensions.settings]
  [[extensions.settings.blocks]]
  type = "atchr_chat"
  name = "Atchr Messaging"
  target = "body"