[build]
  command = "npm run build"
  publish = "build/client"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/webhooks/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"