[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors https://*.myshopify.com https://admin.shopify.com;"
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/server"
  status = 200
  # Add this to ensure auth callbacks work properly
  force = true

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/server" 
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/webhooks/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"