client_id = "2c9d5e5206534a079a8e5ee0ef97a989"
name = "Atchr Messaging"
handle = "atchr-messaging"
application_url = "https://store.atchr.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  # Compliance webhooks (required for App Store)
  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[access_scopes]
scopes = ""

[auth]
redirect_urls = [
  "https://store.atchr.com/auth/callback",
  "https://store.atchr.com/auth/shopify/callback",
  "https://store.atchr.com/api/auth/callback"
]

[pos]
embedded = false
