client_id = "2c9d5e5206534a079a8e5ee0ef97a989"
name = "Atchr Messaging"
handle = "atchr-messaging"
application_url = "https://store.atchr.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
scopes = ""

[auth]
redirect_urls = [
  "https://store.atchr.com/auth/callback"
]

[pos]
embedded = false
