# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2c9d5e5206534a079a8e5ee0ef97a989"
name = "Atchr Messaging"
handle = "atchr-messaging"
application_url = "https://possibly-manually-please-pacific.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "atchr.myshopify.com"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://possibly-manually-please-pacific.trycloudflare.com/auth/callback",
  "https://possibly-manually-please-pacific.trycloudflare.com/auth/shopify/callback",
  "https://possibly-manually-please-pacific.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
