client_id = "2c9d5e5206534a079a8e5ee0ef97a989"
name = "Atchr Messaging"
handle = "atchr-messaging"
application_url = "https://atchr.netlify.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
scopes = ""

[auth]
redirect_urls = [
  "https://atchr.netlify.app/auth/callback",
  "https://atchr.netlify.app/auth/shopify/callback",
  "https://atchr.netlify.app/api/auth/callback"
]

[pos]
embedded = false
